---
packages:
- name: redis
  version: 1
  sha1: !binary |-
    OGJlZjUyYzQ2ZmRlNWI5ZWMwYzliYzVkY2I2YjQ2MjYxYmYzYTEwOA==
  fingerprint: !binary |-
    MDY3Y2QwMjVmNjFlZjAxNjI1NzFhYTg2NTQwYTE1OGMwOWE3YzM2Ng==
  dependencies: []
jobs:
- name: redis
  version: 1
  fingerprint: !binary |-
    ODk5Mzk1NzViM2ZkZGZlYjc4ZTk0NjNiNmI2Y2E5MDY3ZTczMDI2Zg==
  sha1: !binary |-
    MmRmNzYwY2I0ZGJiODdhYzE0YTBiZGMwYzBhNTU5OTc2NWViMzU2Mg==
commit_hash: 59e77715
uncommitted_changes: true
name: redis
version: 1
